### ISSUE TITLE
Add WX300+ to Plugin

### ISSUE THREAD

**Issue by k5sql** [DoctorMcKay/HSPI_WX200MultiStatus#2]
Need support for new WX300+ switch on plugin. Looking at the code briefly, it seems possible based on how the devices are being verified. I'm not an expert at HS device handling, nor the language you are using, however.

**Comment by DoctorMcKay** [comment]
I don't have any WX300 switches so I won't be able to add support if I can't test it against them.

**Comment by k5sql** [comment]
I have three. I like the idea of your plugin and want to see it keep going. How can I help? I don't want to just fork it, figure it out myself, and steal the thunder or anything. I'm willing to beta test, branch it, send back testing results etc.

Just let me know what I can do. Currently and off-topicly, I'm pulling my hair out trying to make S2 function on my network after the 3.0.9.0 debacle and I'm about to reset everything and disable S2 because load control on the wx300 is non functional from software at the moment. 

Let me know what I can do to help/test/etc and I'll get started soon as I reset my network.
