### ISSUE TITLE
Timeout/No Action after Upgrade to HS4 v4 ZWave Plugin

### ISSUE THREAD

**Issue by k5sql** [DoctorMcKay/HSPI_WX200MultiStatus#4]
Not sure where to throw dirty looks for this one - be it that the 'new' ZWave plugin HS pushed out is tagged 'beta' ("dont use beta!") or if it is due to the radical changes they made (they've essentially stated this new plugin completely whacks the event system...

Ever since hesitantly taking the upgrade offer and installing the v4 plugin despite my better judgment, the LEDs don't update as they should 100% of the time. I am finding that out of my 3 switches, which are all in the same group:
- Let's call them Switches S1, S2, and S3
- S1 and S2 fail to update any LEDs all of the time (0% success)
- S3 will update LED 1 some of the time (50% success)
- S3 will update LED 2 even less frequently (30% success)

The curious bit is I started noticing seeing this in the logs and why I questioned this being the fault of the shiny new v4 zwave plugin:
_Error while executing PluginFunction Configuration_Set with 5 parameters - Timeout occured. Did not receive a response._

A bit about what I do with it right now (I'll spare my usual lengthy ramble about WHY and just skip to the WHAT):
- If the garage door is raised, set LED 1 to RED. 
- If the door is lowered, set LED 2 to BLUE. 
  - This uses a Z-Wave garage door controller to trigger an event based on the barrier operator status. 
  - HS is correctly detecting the barrier operator status.
  - An event is triggered upon the operator status change, which calls a separate event that runs the plugin command. I did it this way to provide changing the things that set the light color and/or allow multiple things to set the same light color if desired.
- If the security system is _changed to_ disarmed, set LED 2 to green.
- If the security system is _changed to_ armed-stay, set LED 2 to blue.
- If the security system is _changed to_ armed-away, set LED 2 to yellow.
- If the security system's status is _changed to_ burglary alarm, set LED 2 to blinking magenta.
- If the security system's status is _changed to_ fire alarm, set LED 2 to blinking red.
  - This uses a AD2Serial (Honeywell Vista Plugin) and associated events.
  - Just like the barrier operator, HS shows it is correctly detecting the status changes.
  - And just like the barrier operator, I have the security system set to trigger its own set of events, to do its own other set of things as well as call the LED changes. 
  - S1 and S2 never set their LED color whatsoever. (Could this be the source of the timeout message?)
  - I have also noticed that for whatever reason, a "stuck" state change at S3 (Red->Blue, for example) on the garage door event will _sometimes_ get flushed out by a security system status change - for example, lowering the door fails to change LED1 from Red to Blue. But then, arming the system fails to change the LED2 from Green to Blue *BUT* then magically LED1 has updated.
- Depending on how many different state changes resulting in LED color swaps in a short period, this even has the effect of temporarily blocking access to the web interface (spinning wait) while it does whatever before timing out.

Happy to retrieve whatever logs might be useful in determining if this is HS's fault, -this- plugin's fault, both, or neither; and which side needs to fix something. Depending on sensitivity of data to be retrieved, I can send on Keybase if necessary.

**Comment by DoctorMcKay** [comment]
The new z-wave plugin is almost certainly architected in such a way that it's not compatible with this plugin as-is. For starters, the HS4 docs indicate that there are two different ways to communicate with a different plugin depending on whether it's a legacy or HS4-native plugin. I'm not entirely sure that it's even possible to support both the legacy z-wave plugin and the new one in the same build of this plugin.

Either way, it's up to me to update this plugin to be compatible, assuming it's possible of course. I haven't yet worked up the nerve to install the new z-wave plugin on my own system. I do have access to a test system, and I'm just now remembering that I also have a spare z-wave dongle somewhere, so in theory I should be able to make this work without updating my own personal system.

I'll see when I can find the time to pursue this.
